### ISSUE TITLE
rdp Win2003,show ERROR:	NODE_RDP_PROTOCOL_X224_NEG_FAILURE()

### ISSUE THREAD

**Issue by zhoutianwu** [citronneur/node-rdpjs#22]
rdp Win2003 ,show error:
[node-rdpjs] ERROR: NODE_RDP_PROTOCOL_X224_NEG_FAILURE()
Error
    at new ProtocolError (file:///C:/Users/Administrator/Hozz5/app/main.js:138510:9)
    at Client.recvConnectionConfirm (file:///C:/Users/Administrator/Hozz5/app/main.js:156822:10)
    at TPKT.<anonymous> (file:///C:/Users/Administrator/Hozz5/app/main.js:156803:9)
    at TPKT.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at TPKT.emit (events.js:188:7)
    at TPKT.recvData (file:///C:/Users/Administrator/Hozz5/app/main.js:137623:8)
    at BufferLayer.<anonymous> (file:///C:/Users/Administrator/Hozz5/app/main.js:137614:9)
    at BufferLayer.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at BufferLayer.emit (events.js:188:7)
    at BufferLayer.recv (file:///C:/Users/Administrator/Hozz5/app/main.js:137821:9)
    at Socket.<anonymous> (file:///C:/Users/Administrator/Hozz5/app/main.js:137771:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)

**Comment by citronneur** [comment]
This is because node rdp doesn't support old version of RDP protocol.

**Comment by StefanScherer** [comment]
Change the settings on your server like this:

<img width="416" alt="bildschirmfoto_2016-11-04_um_07_53_42" src="https://cloud.githubusercontent.com/assets/207759/19997024/ecffd37e-a263-11e6-8124-80d3a4db4aca.png">

**Comment by citronneur** [comment]
Hi,

This is because old RDP protocol is not supported on node-rdpjs.

Sorry

**Comment by Karthikrajit** [comment]
I  set  Allow remote connections to this computer. But still it throws same error. Old RDP  protocol is not supported  on node-rdpjs, so how can we solved this issue. My destination server is windows 2012 r2

**Comment by sonianand11** [comment]
After doing configuration in machine, it works for me. However I have dynamic server creation in cloud and I can't go into server every time and change configuration. Which windows OS is supported @citronneur  ?

Following is my windows machine configuration
![screencapture-localhost-9250-1497511827125](https://user-images.githubusercontent.com/614337/27170242-dc9ce69a-51ca-11e7-8a82-be1fa1fcd2e2.png)
 
UPDATE :
I have checked version of RDP and it shows me 10.2.
![screencapture-localhost-9250-1497514111871](https://user-images.githubusercontent.com/614337/27171820-8158eb34-51d0-11e7-840b-e7fa208c3994.png)

**Comment by StefanScherer** [comment]
@sonianand11 You can add the following line to your provisioning of your cloud servers

```
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
```

After that I was able to use node-rdpjs with a Windows Server 2016 running in Azure.

**Comment by sonianand11** [comment]
@StefanScherer Thank you for reply. I am also using azure. I am creating windows instance by Ruby SDK . Can you please also suggest which part of configuration I need to add that line ?

**Comment by StefanScherer** [comment]
@sonianand11 I don't know the Ruby client, but I can show you how to run scripts within a "Deploy to Azure button" configuration [azuredeploy.json](https://github.com/StefanScherer/docker-windows-azure/blob/0b1d7cf8cbbccaad797658599c9f9b1113377d09/azuredeploy.json#L238-L240) I did a while ago in [github.com/StefanScherer/docker-windows-azure](https://github.com/StefanScherer/docker-windows-azure/tree/0b1d7cf8cbbccaad797658599c9f9b1113377d09) repo.

**Comment by sonianand11** [comment]
@StefanScherer Thank you. This helps me. I will look more into it. I will also update if anything works for me via Ruby SDK

**Comment by citronneur** [comment]
I think ntlm auth la needed but not implemented . In next release.

**Comment by kochecc2** [comment]
What are the roadblocks to supporting older versions of the rdp protocol? I've been wanting to help code something, and I think adding support for this could be a good place to start.

**Comment by activeliang** [comment]
> @sonianand11您可以将以下行添加到您的云服务器配置中
> 
> ```
> reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
> ```
> 
> 之后，我能够在 Azure 中运行的 Windows Server 2016 中使用 node-rdpjs。

it works, thx
